[pytest]
testpaths = tests_e2e
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html
filterwarnings =
    ignore::DeprecationWarning
    ignore::sqlalchemy.exc.SAWarning
