"""initial

Revision ID: 7478758a6028
Revises: 
Create Date: 2026-05-22 01:55:08.311718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7478758a6028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', name='status_pessoa_enum'), nullable=False),
    sa.Column('tipo', sa.Enum('paciente', 'medico', name='tipo_pessoa_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('perfil', sa.Enum('gestor', 'recepcionista', 'medico', 'paciente', name='perfil_enum'), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', name='status_usuario_enum'), nullable=False),
    sa.Column('modulos_permitidos', sa.JSON(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('modulo', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('resultado', sa.Enum('sucesso', 'falha', name='resultado_auditoria_enum'), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=False),
    sa.Column('data_formatura', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('convenio', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_ponto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('entrada', sa.Time(), nullable=True),
    sa.Column('saida', sa.Time(), nullable=True),
    sa.Column('h_trabalhadas', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('h_esperadas', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('diferenca', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('situacao', sa.Enum('normal', 'atraso', 'falta', 'h_extra', name='situacao_ponto_enum'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('tipo_consulta', sa.String(), nullable=False),
    sa.Column('convenio', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('agendada', 'confirmada', 'realizada', 'cancelada', name='status_consulta_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cid', sa.String(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('prescricao', sa.Text(), nullable=False),
    sa.Column('retorno_em_dias', sa.Integer(), nullable=False),
    sa.Column('laudo_liberado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos_financeiros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('servico', sa.String(), nullable=False),
    sa.Column('convenio', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pago', 'pendente', 'atrasado', name='status_financeiro_enum'), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos_financeiros')
    op.drop_table('prontuarios')
    op.drop_table('consultas')
    op.drop_table('registros_ponto')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('log_auditoria')
    op.drop_table('usuarios')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
